---
title: C6322
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6322
helpviewer_keywords:
- C6322
ms.assetid: fb23d2b1-b2a0-465c-8bf5-ec039c6c7757
ms.openlocfilehash: 0f228d7edc91344dea1e30e1e78c340a81a97053
ms.sourcegitcommit: a1676bf6caae05ecd698f26ed80c08828722b237
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 09/29/2020
ms.locfileid: "91509156"
---
# <a name="c6322"></a>C6322

> Uyarı C6322: boş _except bloğu

Bu ileti _except bloğunda kod olmadığını gösterir. Sonuç olarak, özel durumlar işlenmemiş duruma gelebilir.

## <a name="example"></a>Örnek

Aşağıdaki kod bu uyarıyı oluşturur:

```cpp
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void fd(char *pch)
{
   __try
   {
     // exception rasied if pch is null
     *pch= 0 ;
   }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION)
   {
   }
}
```

Bu uyarıyı düzeltmek için aşağıdaki kodu kullanın:

```cpp
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void f(char *pch)
{
   __try
   {
     // exception rasied if pch is null
    *pch= 0 ;
   }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
     // code to handle exception
     puts("Exception Occurred");
   }
}
```

## <a name="see-also"></a>Ayrıca bkz.

[try-except ekstresi](../cpp/try-except-statement.md)
